version: '3.8'
services:
    # vetsytemsdb:
    #     image: mcr.microsoft.com/mssql/server:2019-latest
        
    gateway.api:
        image:  gateway_api_image
        build:
            context: .
            dockerfile: ApiGateways/BrewCloud.Gateway/Dockerfile    
    identityserver.api:
        image: identityserver_api_image
        build: 
            context: .
            dockerfile: Services/IdentityServer/BrewCloud.IdentityServer/Dockerfile
    account.api:
        image: account_api_image
        build: 
            context: .
            dockerfile: Services/Account/BrewCloud.Account/Dockerfile
    vet.api:
        image: vet_api_image
        build:
            context: .
            dockerfile: Services/Vet/BrewCloud.Vet.Api/BrewCloud.Vet.Api/Dockerfile
    farm.api:
        image: farm_api_image
        build:
            context: .
            dockerfile: Services/Farm/BrewCloud.Farm.Api/Dockerfile
    mail.api:
        image: mail_api_iamge
        build:
            context: .
            dockerfile: Services/Mail/BrewCloud.Mail.Api/Dockerfile
    chat.api:
        image: chat_api_image
        build:
            context: .
            dockerfile: Services/Chat/BrewCloud.Chat.Api/Dockerfile
    integrations.api:
        image: integrations_api_image
        build:
            context: .
            dockerfile: Services/Integrations/BrewCloud.Integrations.Api/Dockerfile
    mobile.api:
        image: mobile_api_image
        build:
            context: .
            dockerfile: Services/Mobile/BrewCloud.Mobile.Api/Dockerfile
    gym.api:
        image: gym_api_image
        build:
            context: .
            dockerfile: Services/Gym/BrewCloud.Gym.Api/Dockerfile
    hubs.api:
        image: hubs_api_image
        build:
            context: .
            dockerfile: Services/Hubs/BrewCloud.Hubs.Api/Dockerfile

volumes:
  identitydb_volume:
        
  