version: '3.8'
services:
    # vetsytemsdb:
    #     container_name: vetsytemsdb
    #     restart: always
    #     ports:
    #         - "1433:1433" 
    #     environment:
    #         - ACCEPT_EULA=Y
    #         - SA_PASSWORD=123654Dg  
      
    gateway.api:
        container_name: gateway.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - identityserver.api
            - account.api
        ports:
            - "5000:80"    
    identityserver.api:
        container_name: identityserver.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings:DefaultConnection=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
            - EventBusSettings:HostAddress=amqps://ebgfgaha:DCwUehyMQDtR0oeiqYJDCn-T4VEYhXY7@stingray.rmq.cloudamqp.com/ebgfgaha
            - VetDbSettings:ServerName=mssql-172240-0.cloudclusters.net,10023
            - VetDbSettings:User=vet
            - VetDbSettings:Password=123654Dg
            - GRPC_PORT=81
            - PORT=80 
            - ApiGatewayUrl=http://gateway.api/services/
        ports:
            - "5001:80"
    account.api:
        container_name: account.api
        restart: on-failure
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings:ConnectionString=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
            - "EventBusSettings:HostAddress=amqps://ebgfgaha:DCwUehyMQDtR0oeiqYJDCn-T4VEYhXY7@stingray.rmq.cloudamqp.com/ebgfgaha" 
            - IdentityServerURL=http://identityserver.api:80
            - GrpcSettings:IdentityUrl=http://identityserver.api:81
            - VetDbSettings:ServerName=mssql-172240-0.cloudclusters.net,10023
            - VetDbSettings:User=vet
            - VetDbSettings:Password=123654Dg
        depends_on:
            - identityserver.api
        ports:
            - "5012:80" 
    # vet.api:
    #     container_name: vet.api
    #     restart: on-failure
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Development
    #         - ConnectionStrings:ConnectionString=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
    #         - IdentityServerURL=http://identityserver.api:80
    #         - GrpcSettings:IdentityUrl=http://identityserver.api:81
    #         - ApiGatewayUrl=http://gateway.api/services/
    #     ports:
    #         -  "5013:80"
    # farm.api:
    #     container_name: farm.api
    #     restart: on-failure
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Local
    #         - ConnectionStrings:DefaultConnection=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
    #     ports:
    #         -  "5016:80"
    # mail.api:
    #     container_name: mail.api
    #     restart: on-failure
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Local
    #         - ConnectionStrings:ConnectionString=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
    #         - IdentityServerURL=http://identityserver.api:80 
    #         - GrpcSettings:IdentityUrl=http://identityserver.api:81
    #     ports:
    #         - "5018:80"
    # chat.api:
    #     container_name: chat.api
    #     restart: on-failure
    #     environment: 
    #         - ASPNETCORE_ENVIRONMENT=Development
    #         - ConnectionStrings:DefaultConnection=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
    #         - VetDbSettings:ServerName=mssql-172240-0.cloudclusters.net,10023
    #         - VetDbSettings:User=vet
    #         - VetDbSettings:Password=123654Dg
    #         - IdentityServerURL=http://identityserver.api:80
    #         - GrpcSettings:IdentityUrl=http://identityserver.api:81
    #     ports:
    #         - "5017:80"  
    # integrations.api:
    #     container_name: integrations.api
    #     restart: on-failure
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Local
    #         - ConnectionStrings:DefaultConnection=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
    #         - VetDbSettings:ServerName=mssql-172240-0.cloudclusters.net,10023
    #         - VetDbSettings:User=vet
    #         - VetDbSettings:Password=123654Dg
    #     ports:
    #         - "5015:80"  
    # mobile.api:
    #     container_name: mobile.api
    #     restart: on-failure
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Local
    #         - ConnectionStrings:DefaultConnection=Server=mssql-172240-0.cloudclusters.net,10023; Database=vet-5cdb0c05-0cc5-4bef-b28d-d27cc5b56017;User Id=vet;Password=123654Dg
    #     ports:
    #         - "5014:80" 

            

 

    