version: '3.8'
services:
    vetsytemsdb:
        container_name: vetsytemsdb
        restart: always
        ports:
            - "1433:1433" 
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=123654Dg  
      
    gateway.api:
        container_name: gateway.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - identityserver.api
        ports:
            - "5000:80"    
    identityserver.api:
        container_name: identityserver.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:DefaultConnection=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123654Dg
            - VetDbSettings:ServerName=vetsytemsdb,1433
            - VetDbSettings:User=sa
            - VetDbSettings:Password=123654Dg
            - GRPC_PORT=5010
            - PORT=5001 
        ports:
            - "5001:80"
    account.api:
        container_name: account.api
        restart: on-failure
        environment: 
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:ConnectionString=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123D654Dg
            - IdentityServerURL=http://identityserver.api
            - GrpcSettings:IdentityUrl=http://identityserver.api
        ports:
            - "5012:80" 
    vet.api:
        container_name: vet.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:ConnectionString=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123D654Dg
            - IdentityServerURL=http://identityserver.api  
        ports:
            -  "5013:80"
    farm.api:
        container_name: farm.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:DefaultConnection=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123D654Dg
        ports:
            -  "5016:80"
    mail.api:
        container_name: mail.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:DefaultConnection=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123D654Dg
        ports:
            - "5018:80"
    chat.api:
        container_name: chat.api
        restart: on-failure
        environment: 
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:DefaultConnection=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123D654Dg
        ports:
            - "5017:80"  
    integrations.api:
        container_name: integrations.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:DefaultConnection=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123D654Dg
        ports:
            - "5015:80"  
    mobile.api:
        container_name: mobile.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Local
            - ConnectionStrings:DefaultConnection=Server=vetsytemsdb,1433; Database=VetAdminIdentityDb; User=sa; Password=123D654Dg
        ports:
            - "5014:80" 

            

 

    