// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetSystems.Vet.Infrastructure.Persistence;

#nullable disable

namespace VetSystems.Vet.Infrastructure.Migrations
{
    [DbContext(typeof(VetDbContext))]
    [Migration("20230827225648_updatedata_2")]
    partial class updatedata_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetAdress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("county");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district");

                    b.Property<string>("LongAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("longadress");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("pk_vetadress");

                    b.ToTable("vetadress", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetAnimalBreedsDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnimalType")
                        .HasColumnType("int")
                        .HasColumnName("animaltype");

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("breedname");

                    b.HasKey("Id")
                        .HasName("VetAnimalBreedsDef_pkey");

                    b.ToTable("vetanimalbreedsdef", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetAnimalColorsDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("VetAnimalColorsDef_pkey");

                    b.ToTable("vetanimalcolorsdef", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetAnimalsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("VetAnimalsType_pkey");

                    b.ToTable("vetanimalstype", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetCasingDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("casename");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<bool?>("Durumu")
                        .HasColumnType("bit")
                        .HasColumnName("durumu");

                    b.Property<string>("Kasa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kasa");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetCasingDefinition_pkey");

                    b.ToTable("vetcasingdefinition", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetCustomerGroupDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetCustomerGroupDef_pkey");

                    b.ToTable("vetcustomergroupdef", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetCustomers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AdressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("adressid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<Guid?>("CustomerGroup")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customergroup");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discountrate");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstname");

                    b.Property<bool?>("IsEmail")
                        .HasColumnType("bit")
                        .HasColumnName("isemail");

                    b.Property<bool?>("IsPhone")
                        .HasColumnType("bit")
                        .HasColumnName("isphone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastname");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("PhoneNumber2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phonenumber2");

                    b.Property<string>("TaxOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("taxoffice");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.Property<string>("VKNTCNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vkntcno");

                    b.HasKey("Id")
                        .HasName("VetCustomers_pkey");

                    b.HasIndex("AdressId")
                        .HasDatabaseName("ix_vetcustomers_adressid");

                    b.ToTable("vetcustomers", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetParameters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool?>("AutoSms")
                        .HasColumnType("bit")
                        .HasColumnName("autosms");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetParameters_pkey");

                    b.ToTable("vetparameters", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetPatients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("AnimalBreed")
                        .HasColumnType("int")
                        .HasColumnName("animalbreed");

                    b.Property<int>("AnimalColor")
                        .HasColumnType("int")
                        .HasColumnName("animalcolor");

                    b.Property<int?>("AnimalType")
                        .HasColumnType("int")
                        .HasColumnName("animaltype");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthdate");

                    b.Property<string>("ChipNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chipnumber");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customerid");

                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customersid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<byte?>("Images")
                        .HasColumnType("tinyint")
                        .HasColumnName("images");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("ReportNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reportnumber");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("specialnote");

                    b.Property<bool>("Sterilization")
                        .HasColumnType("bit")
                        .HasColumnName("sterilization");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetPatients_pkey");

                    b.HasIndex("CustomersId")
                        .HasDatabaseName("ix_vetpatients_customersid");

                    b.ToTable("vetpatients", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetProductCategories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("categorycode");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetProductCategories_pkey");

                    b.ToTable("vetproductcategories", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("AnimalType")
                        .HasColumnType("int")
                        .HasColumnName("animaltype");

                    b.Property<bool?>("BuyingIncludeKDV")
                        .HasColumnType("bit")
                        .HasColumnName("buyingincludekdv");

                    b.Property<decimal>("BuyingPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("buyingprice");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("categoryid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<decimal>("CriticalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("criticalamount");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<bool?>("FixPrice")
                        .HasColumnType("bit")
                        .HasColumnName("fixprice");

                    b.Property<bool?>("IsExpirationDate")
                        .HasColumnType("bit")
                        .HasColumnName("isexpirationdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberRepetitions")
                        .HasColumnType("int")
                        .HasColumnName("numberrepetitions");

                    b.Property<string>("ProductBarcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productbarcode");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productcode");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("producttypeid");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ratio");

                    b.Property<bool?>("SellingIncludeKDV")
                        .HasColumnType("bit")
                        .HasColumnName("sellingincludekdv");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sellingprice");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplierid");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("unitid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("Vetproducts_pkey");

                    b.ToTable("vetproducts", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetStores", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<string>("DepotCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("depotcode");

                    b.Property<string>("DepotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("depotname");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetStores_pkey");

                    b.ToTable("vetstores", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetSuppliers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("suppliername");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetSuppliers_pkey");

                    b.ToTable("vetsuppliers", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetUnits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdate");

                    b.Property<string>("CreateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createusers");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleteddate");

                    b.Property<string>("DeletedUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedusers");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unitcode");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unitname");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedate");

                    b.Property<string>("UpdateUsers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updateusers");

                    b.HasKey("Id")
                        .HasName("VetUnits_pkey");

                    b.ToTable("vetunits", (string)null);
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetCustomers", b =>
                {
                    b.HasOne("VetSystems.Vet.Domain.Entities.VetAdress", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vetcustomers_vetadress_adressid");

                    b.Navigation("Adress");
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetPatients", b =>
                {
                    b.HasOne("VetSystems.Vet.Domain.Entities.VetCustomers", "Customers")
                        .WithMany("Patients")
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vetpatients_vetcustomers_customersid");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("VetSystems.Vet.Domain.Entities.VetCustomers", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
