name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22

    - name: Pull latest changes from GitHub
      run: |
         cd /VetSystems/
         git pull origin master

    - name: Restart Docker Compose
      run: |
        cd /VetSystems/
        docker-compose down
        docker-compose pull
        docker-compose up -d
