name: Deploy to DigitalOcean with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install doctl
      run: sudo snap install doctl

    - name: Authenticate with DigitalOcean
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

    - name: Deploy to DigitalOcean Droplet
      env:
        DIGITALOCEAN_IP: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
        DIGITALOCEAN_SSH_USER: ${{ secrets.DIGITALOCEAN_SSH_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no ${DIGITALOCEAN_SSH_USER}@${DIGITALOCEAN_IP} << 'EOF'
          cd /path/to/your/project
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          exit
        EOF
