name: Deploy to DigitalOcean with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install doctl
      run: sudo snap install doctl

    - name: Authenticate with DigitalOcean
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

    - name: Retrieve Droplet ID
      id: droplet
      run: doctl compute droplet list --format ID,Name --no-header | grep "your-droplet-name" | awk '{print $1}'

    - name: Deploy to DigitalOcean Droplet
      env:
        DROPLET_ID: ${{ steps.droplet.outputs.result }}
      run: |
        doctl compute ssh ${DROPLET_ID} --ssh-command "
          cd /path/to/your/project &&
          git pull origin main &&
          docker-compose down &&
          docker-compose up -d --build
        " --ssh-port 22 --ssh-user ${{ secrets.DIGITALOCEAN_SSH_USER }} --ssh-key-path ~/.ssh/id_rsa
